name: "Build OctoDev Optimized"

on:
  push:
    branches:
      - main

jobs:
  publish-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' 

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target

      - name: install dependencies (ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: install frontend dependencies
        run: npm install

      - name: setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: setup Android SDK
        uses: android-actions/setup-android@v3
        with:
            build-tools: "29.0.3"
            
      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: build android apk
        run: npx tauri android build --debug
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=1g"

      - name: Find APK Path
        id: find_apk
        run: |
          # Busca o arquivo APK gerado dentro da pasta gen/android
          APK_FILE=$(find src-tauri/gen/android -name "*.apk" | head -n 1)
          APK_DIR=$(dirname "$APK_FILE")
          echo "dir=$APK_DIR" >> $GITHUB_OUTPUT
          echo "Sucesso: APK encontrado em $APK_DIR"

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: ${{ steps.find_apk.outputs.dir }}
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASS }}

      - name: upload signed apk
        uses: actions/upload-artifact@v4
        with:
          name: OctoDev-Signed
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}

      - name: upload unsigned apk (fallback)
        uses: actions/upload-artifact@v4
        with:
          name: OctoDev-Unsigned
          path: src-tauri/gen/android/**/*.apk